ready to format

diff --git a/takeout b/takeout
--- a/takeout
+++ b/takeout
@@ -1,42 +1,28 @@
 #!//bin/sh -e
 
-# extract_app='/System/Library/CoreServices/Applications/Archive Utility.app'
+source="/Users/amatiasq/Downloads"
+destination="/Volumes/home"
+file="$source/$1"
 
-# dir='/Volumes/home/TAKEOUT'
-# id='20220922T065118Z'
-# extension='.tgz'
+if [ ! -f "$file" ]; then
+  if [ ! -d "Takeout" ]; then
+    echo "File not found: $file"
+    exit 1
+  else
+    echo cp -r Takeout "$destination"
+    cp -r Takeout "$destination"
+    echo "Removing Takeout dir..."
+    rm -r Takeout
+    exit 0
+  fi
+fi
 
-# target_dir='/Users/amatiasq/Documents/TAKEOUT'
+echo tar -xzf "$file"
+tar -xzf "$file" > /dev/null
+echo "Removing $file..."
+rm "$file"
 
-# for i in {3..29}
-# do
-#   pad_left="00${i}"
-#   number="${pad_left: -3}"
-
-#   source="${dir}/takeout-${id}-${number}${extension}"
-#   target="${target_dir}/${number}${extension}"
-
-
-#   echo $source
-#   open -W "$extract_app" "$source"
-#   rm "$source"
-
-#   # uncompressed="${target_dir}/${number}"
-
-#   # # echo "Copying ${number}..."
-#   # echo cp -v "$source" "$target"
-#   # # echo "Uncompressing ${number}..."
-#   # echo open -W '/System/Library/CoreServices/Applications/Archive Utility.app' "$target"
-#   # # echo "Deleting ${number}..."
-#   # echo rm "$target"
-#   # # echo "Done ${number}."
-# done
-
-
-
-# for i in {4..29}
-# do
-#   dir="Takeout $i"
-#   cp -r "$dir/" Takeout
-#   rm -r "$dir"
-# done
+echo cp -r Takeout "$destination"
+cp -r Takeout "$destination"
+echo "Removing Takeout dir..."
+rm -r Takeout
